#!/bin/bash

## run a solution

usage() {
        local exitcode=${1:-1}

        echo "usage: aoc-run [ -y <year> ] [ -d <day> ] [ -t <tag> ]"
        echo ""
        echo "Runs code for a year and day."
        echo ""
        echo "Options:"
        echo "* -y -- year (defaults to current year)"
        echo "* -d -- day (defaults to current day)"
        echo "* -t -- tag for Docker image (defaults to 'latest')"

        exit "${exitcode}"
}

while getopts ":d:ht:y:" opt; do
        case ${opt} in
        d) # day
                AOC_DAY=${OPTARG}
                ;;

        h) # help
                usage 0
                ;;

        t) # tag for lang image
                AOC_TAG=${OPTARG}
                ;;

        y) # year
                AOC_YEAR=${OPTARG}
                ;;

        \?)
                echo "invalid option -${OPTARG}" 1>&2
                usage
                ;;

        :)
                echo "option ${OPTARG} requires an argument" 1>&2
                usage
                ;;
        esac
done
shift $((OPTIND - 1))

# for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
CURRENT_YEAR=$(date -I | cut -d '-' -f 1)
# for Linux? CURRENT_DAY=$(date --iso-8601 | cut -d '-' -f 3)
CURRENT_DAY=$(date -I | cut -d '-' -f 3)

AOC_DAY=${AOC_DAY:-${CURRENT_DAY}}
AOC_TAG=${AOC_TAG:-latest}
AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}

if [[ -z "${AOC_YEAR}" ]]; then
        usage
elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
        echo "year out of range"
        usage
elif [[ -z "${AOC_DAY}" ]]; then
        usage
fi

# strip leading zero, if any, for proper numeric comparisons
if [[ -n "${AOC_DAY}" ]]; then
        AOC_DAY=$(echo "${AOC_DAY}" | sed -E 's/^0//')
        AOC_DAY=$((AOC_DAY + 0))
fi

if ((AOC_DAY < 1 || AOC_DAY > 25)); then
        echo "day out of range"
        usage
elif ((AOC_YEAR == CURRENT_YEAR && AOC_DAY > CURRENT_DAY)); then
        echo "day ${AOC_DAY} hasn't been released yet"
        usage
fi

# now that we're done comparing numbers, force day to two digits
AOC_DAY=$(printf "%02d" "${AOC_DAY}")

docker run \
        --interactive \
        --mount type=bind,src="./years/${AOC_YEAR}/elixir",dst=/aoc/src \
        --mount type=bind,src="./years/${AOC_YEAR}/data",dst=/aoc/data \
        --mount type=volume,src="aoc-elixir-${AOC_YEAR}-build",dst=/aoc/src/_build \
        --mount type=volume,src="aoc-elixir-${AOC_YEAR}-deps",dst=/aoc/src/deps \
        --mount type=volume,src="aoc-elixir-${AOC_YEAR}-mix",dst=/home/aoc/.mix \
        --name aoc-elixir \
        --rm \
        --tty \
        "ghcr.io/krisalyssa/aoc/aoc-elixir:${AOC_TAG}" \
        -c "bin/run ${AOC_DAY}"
