#!/bin/bash

## start a REPL

usage() {
  local exitcode=${1:-1}

  echo "usage: aoc-repl [ -y <year> ] [ -t <tag> ]"
  echo ""
  echo "Starts a Clojure repl for a year."
  echo ""
  echo "Options:"
  echo "* -y -- year (defaults to current year)"
  echo "* -t -- tag for Docker image (defaults to 'latest')"

  exit ${exitcode}
}

while getopts ":ht:y:" opt; do
  case ${opt} in
    h ) # help
      usage 0
      ;;

    t ) # tag for lang image
      AOC_TAG=${OPTARG}
      ;;

    y ) # year
      AOC_YEAR=${OPTARG}
      ;;

    \? )
      echo "invalid option -${OPTARG}" 1>&2
      usage
      ;;

    : )
      echo "option ${OPTARG} requires an argument" 1>&2
      usage
      ;;
  esac
done
shift $((OPTIND -1))

# for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
CURRENT_YEAR=$(date -I | cut -d '-' -f 1)

AOC_TAG=${AOC_TAG:-latest}
AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}

if [[ -z "${AOC_YEAR}" ]]; then
  usage
elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
  echo "year out of range"
  usage
fi

docker run \
  --interactive \
  --mount type=bind,src=./years/${AOC_YEAR}/elixir,dst=/aoc/src \
  --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
  --mount type=volume,src=aoc-elixir-${AOC_YEAR}-build,dst=/aoc/src/_build \
  --mount type=volume,src=aoc-elixir-${AOC_YEAR}-deps,dst=/aoc/src/deps \
  --mount type=volume,src=aoc-elixir-${AOC_YEAR}-mix,dst=/home/aoc/.mix \
  --name aoc-elixir \
  --rm \
  --tty \
  ghcr.io/krisalyssa/aoc/aoc-elixir:${AOC_TAG} \
  -c "bin/repl ${AOC_DAY}"
