#!/bin/bash

## start a container for a language

usage() {
  local exitcode=${1:-1}

  echo "usage: aoc-start [ -y <year> ] [ -t <tag> ] [ -d ]"
  echo ""
  echo "Starts a Docker container with data files mounted."
  echo ""
  echo "Options:"
  echo "* -y -- year (defaults to current year)"
  echo "* -t -- tag for language Docker image (defaults to 'latest')"
  echo "* -d -- detach the container (run it in the background)"
  echo ""
  echo "NOTE: -d does not take a value and is not used to specify a day, unlike other commands."

  exit ${exitcode}
}

while getopts ":dhl:t:y:" opt; do
  case ${opt} in
    d ) # detach
      DETACH=true
      ;;

    h ) # help
      usage 0
      ;;

    t ) # tag for lang image
      AOC_TAG=${OPTARG}
      ;;

    y ) # year
      AOC_YEAR=${OPTARG}
      ;;

    \? )
      echo "invalid option -${OPTARG}" 1>&2
      usage
      ;;

    : )
      echo "option ${OPTARG} requires an argument" 1>&2
      usage
      ;;
  esac
done
shift $((OPTIND -1))

# for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
CURRENT_YEAR=$(date -I | cut -d '-' -f 1)

AOC_TAG=${AOC_TAG:-latest}
AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}

if [[ -z "${AOC_YEAR}" ]]; then
  usage
elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
  echo "year out of range"
  usage
fi

docker run \
  ${DETACH:+--detach} \
  --interactive \
  --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
  --mount type=bind,src=./years/${AOC_YEAR}/clojure,dst=/aoc/src \
  --mount type=volume,src=aoc-clojure-${AOC_YEAR}-m2,dst=/home/aoc/.m2 \
  --mount type=volume,src=aoc-clojure-${AOC_YEAR}-target,dst=/aoc/src/target \
  --name aoc-clojure \
  --tty \
  ghcr.io/krisalyssa/aoc/aoc-clojure:${AOC_TAG} \
  -c "bin/start ${AOC_DAY}"
