#!/bin/bash

## start a container for a language

echo "*** in lang/clojure/start"

usage() {
  local exitcode=${1:-1}

  echo "usage: start [ -y <year> ] [ -t <tag> ]"
  echo ""
  echo "Starts a Docker container for Clojure, with data files mounted."
  echo ""
  echo "Options:"
  echo "* -y -- year (defaults to current year)"
  echo "* -t -- tag for language Docker image (defaults to 'latest')"

  exit ${exitcode}
}

while getopts ":ht:y:" opt; do
  case ${opt} in
    h ) # help
      usage 0
      ;;

    t ) # tag for lang image
      AOC_TAG=${OPTARG}
      ;;

    y ) # year
      AOC_YEAR=${OPTARG}
      ;;

    \? )
      echo "invalid option -${OPTARG}" 1>&2
      usage
      ;;

    : )
      echo "option ${OPTARG} requires an argument" 1>&2
      usage
      ;;
  esac
done
shift $((OPTIND -1))

# for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
CURRENT_YEAR=$(date -I | cut -d '-' -f 1)

AOC_TAG=${AOC_TAG:-latest}
AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}

if [[ -z "${AOC_YEAR}" ]]; then
  usage
elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
  echo "year out of range"
  usage
fi

docker run \
  --interactive \
  --mount type=bind,src=./years/${AOC_YEAR}/clojure,dst=/aoc/src \
  --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
  --name aoc-clojure \
  --platform linux/amd64 \
  --rm \
  --tty \
  ghcr.io/krisalyssa/aoc/aoc-clojure:${AOC_TAG}
