#!/bin/bash

## start a container for a language

usage() {
  local exitcode=${1:-1}

  langs=()
  for filename in $( find lang -type f -name 'Dockerfile' ); do
    langs+=("$( basename $( dirname ${filename} ) )")
  done

  echo "usage: aoc-start [ -y <year> ] [ -t <tag> ]"
  echo ""
  echo "Starts a Docker container with data files mounted."
  echo ""
  echo "Options:"
  echo "* -y -- year (defaults to current year)"
  echo "* -t -- tag for language Docker image (defaults to 'latest')"

  exit ${exitcode}
}

while getopts ":hl:t:y:" opt; do
  case ${opt} in
    h ) # help
      usage 0
      ;;

    t ) # tag for lang image
      AOC_TAG=${OPTARG}
      ;;

    y ) # year
      AOC_YEAR=${OPTARG}
      ;;

    \? )
      echo "invalid option -${OPTARG}" 1>&2
      usage
      ;;

    : )
      echo "option ${OPTARG} requires an argument" 1>&2
      usage
      ;;
  esac
done
shift $((OPTIND -1))

# for Linux? CURRENT_YEAR=$(date --iso-8601 | cut -d '-' -f 1)
CURRENT_YEAR=$(date -I | cut -d '-' -f 1)

AOC_TAG=${AOC_TAG:-latest}
AOC_YEAR=${AOC_YEAR:-${CURRENT_YEAR}}

if [[ -z "${AOC_YEAR}" ]]; then
  usage
elif ((AOC_YEAR < 2015 || AOC_YEAR > CURRENT_YEAR)); then
  echo "year out of range"
  usage
fi

docker run \
  --interactive \
  --mount type=bind,src=./years/${AOC_YEAR}/typescript,dst=/aoc/src \
  --mount type=bind,src=./years/${AOC_YEAR}/data,dst=/aoc/data \
  --mount type=volume,src=typescript-${AOC_YEAR}-cache,dst=/home/aoc/.cache \
  --name aoc-typescript \
  --rm \
  --tty \
  ghcr.io/krisalyssa/aoc/aoc-typescript:${AOC_TAG}
