name: build-images
run-name: build docker images
on:
  pull_request:
    paths:
      - lang/**/Dockerfile
  push:
    branches: [main]
    paths:
      - lang/**/Dockerfile
jobs:
  setup:
    name: set up context
    runs-on: ubuntu-latest
    outputs:
      langs: ${{ steps.vars.outputs.langs }}
    steps:
      - name: check out code
        uses: actions/checkout@v4

      # - name: get changed files
      #   id: files
      #   uses: tj-actions/changed-files@v45
      #   with:
      #     since_last_remote_commit: true

      - name: set variables
        id: vars
        shell: bash
        run: |
          langs=()
          for filename in $( find lang -type f -name 'Dockerfile' ); do
            langs+=("$( basename $( dirname ${filename} ) )")
          done
          echo "langs=$( jq --compact-output --null-input '$ARGS.positional' --args -- "${langs[@]}" )" >> "$GITHUB_OUTPUT"

  build:
    name: build images
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: ${{ fromJSON(needs.setup.outputs.langs) }}
        exclude:
          - lang: clojure
    steps:
      - name: check out most recent commit
        uses: actions/checkout@v4

      - name: set variables
        id: vars
        shell: bash
        run: |
          cd lang/${{ matrix.lang }}

          name="aoc-${{ matrix.lang }}"
          echo "name=${name}" >> "${GITHUB_OUTPUT}"

          echo "image=ghcr.io/${{ github.repository }}/${name}" >> "${GITHUB_OUTPUT}"

          release="false"
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] ; then
             release="true"
          fi
          echo "release=${release}" >> "${GITHUB_OUTPUT}"

          echo "short-sha=$( git rev-parse --short HEAD )" >> "${GITHUB_OUTPUT}"

          version=$( grep "LABEL version=" Dockerfile | sed -e 's/LABEL version="\(.*\)"/\1/' -e 's/ //g' )
          if [[ -z "${version// }" ]]; then
             echo - Failed to get version. Be sure you have a label named "version" in your Dockerfile.
             exit 1
          fi
          echo "version=${version}" >> "${GITHUB_OUTPUT}"

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.vars.outputs.release == 'false'
        name: build image for testing
        uses: docker/build-push-action@v6
        with:
          # but see https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
          cache-from: type=registry,ref=${{ steps.vars.outputs.image }}
          cache-to: type=registry,ref=${{ steps.vars.outputs.image }},mode=max
          #
          context: lang/${{ matrix.lang }}
          push: true
          tags: |
            ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.short-sha }}

      - if: steps.vars.outputs.release == 'true'
        name: build image for release
        uses: docker/build-push-action@v6
        with:
          # but see https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
          cache-from: type=registry,ref=${{ steps.vars.outputs.image }}
          cache-to: type=registry,ref=${{ steps.vars.outputs.image }},mode=max
          #
          context: lang/${{ matrix.lang }}
          push: true
          tags: |
            ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.version }}
            ${{ steps.vars.outputs.image }}:latest

      - if: steps.vars.outputs.release == 'true'
        name: create release
        uses: ncipollo/release-action@v1
        with:
          # allowUpdates:
          # artifactErrorsFailBuild:
          # artifacts:
          # artifactContentType:
          # bodyFile:
          # commit:
          # discussionCategory:
          draft: false
          # generateReleaseNotes:
          # makeLatest:
          name: ${{ steps.vars.outputs.name }}:${{ steps.vars.outputs.version }}
          # omitBody:
          # omitBodyDuringUpdate:
          # omitDraftDuringUpdate:
          # omitName:
          # omitNameDuringUpdate:
          # omitPrereleaseDuringUpdate:
          # owner:
          prerelease: false
          # removeArtifacts:
          # replacesArtifacts:
          # repo:
          # skipIfReleaseExists:
          tag: ${{ steps.vars.outputs.name }}:${{ steps.vars.outputs.version }}
          # token:
          # updateOnlyUnreleased:
          body: "`docker pull ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.version }}`"
